In [3]:
# 1] write a code to create a string with your name and print it?
#ans- name = input("please enter your name: ")
#print(f"Name: {name}")

# 2] write a code to find the length of the string "Hello,World"
#ans- #include<stdio.h>
# int main(){
#    print("Hello,World")
#    return 0;
#}

#3] write a code to slice the first three characters from the string "python programming".
#ans- string = 'python programming'
#slice_obj = slice(3, 18)
#print(string[slice_obj])

# 4]write a code to convert the string "hello" to uppercase.
#my_string = "hello"
#uppercase = my_string.upper()
#print(uppercase)

#5] write a code to replace the word "apple" orange in the string "i like apple".
#ans- #string1 = "i like apple"
#string2 = string1.replace("apple", "orange")
#print(string2)

#6] write a code to create a list with numbers 1 to 5 and print it.
#list1 = [1, 2, 3, 4, 5]
#print(list1)

#7] write a code to append the number 10 to the list [1, 2, 3, 4].
#ans- #list1 = [1, 2, 3, 4]
#list1.append(10)

#8]write a code to remove the number 3 from the list[1, 2, 3, 4, 5].
#ans- #list1 = [1, 2, 3, 4, 5]
#list1.remove(3)
#print(list1)

#9] write a code to access second element in the list['a', 'b', 'c','d'].
#list1 = ['a', 'b', 'c' 'd']
#print(list1[1])

#10] write a code to reverse the list [10, 20, 30, 40, 50]
#ans- #list1 = [10, 20, 30, 40, 50]
#list1.reverse()
#print(list1)

#11] write a code to create a tuple with the elements 10,20,30 and print it
#ans- #tuple1 = (10, 20, 30)
#print(tuple1)

#12] write a code to access the first element of the tuple('apple', 'banana', 'cherry').
#ans- #tuple1 = ('apple', 'banana', 'cherry')
#print(tuple1[0])

#13] write a code to count how many times the number 2 apears in the tuple(1,2,3,2,4,2).
#ans- tuple = (1, 2, 3, 2, 4, 2)
#count = tuple.count(2)
#print(count)

#14] write a code to find the index of the element "cat" in the tuple('dog', 'cat', 'rabbit').
#ans- tuple = ('dog', 'cat', 'rabbit')
#index = tuple.index('cat')
#print(index)

# 15] write a code to check if the element 'banana' in the tuple('apple','orange','banana').
#ans- tuple = ('apple', 'orange', 'banana')
#if 'banana' in tuple:
#    print("yes")
#else:
#    print("no")

#16] write a code to create a set with the elements 1, 2, 3, 4, 5 and print it.
#set = {1, 2, 3, 4, 5}
#print(set)

#17]write a code to add the element 6 to the set {1,2,3,4}.
#ans- set = {1, 2, 3, 4}
#set.add(6)
#print(set)

#18] write a code to create a tuple with the elements 10,20,30 and print it.
#tuple = (10, 20, 30)
#print(tuple)

#19] write a code to access the first element of the tuple('apple', 'banana', 'cherry').
#tuple = ('apple', 'banana', 'cherry')
#print(tuple[1])